import React, { createContext, useState, useEffect, useMemo } from 'react';

export const LangContext = createContext({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
});

const translations = {
  en: {
    home: 'Home',
    windows: 'Windows',
    help: 'Help',
    welcome: 'Welcome',
    logout: 'Logout',
    pinned: 'Pinned',
    dashboard: 'Dashboard',
    forms: 'Forms',
    reports: 'Reports',
    settings: 'Settings',
    general: 'General',
    users: 'Users',
    userCompanies: 'User Companies',
    rolePermissions: 'Role Permissions',
    modules: 'Modules',
    changePassword: 'Change Password',
  },
  mn: {
    home: 'Нүүр',
    windows: 'Цонхнууд',
    help: 'Тусламж',
    welcome: 'Тавтай морилно уу',
    logout: 'Гарах',
    pinned: 'Түгжсэн',
    dashboard: 'Хяналтын самбар',
    forms: 'Маягтууд',
    reports: 'Тайлан',
    settings: 'Тохиргоо',
    general: 'Ерөнхий',
    users: 'Хэрэглэгчид',
    userCompanies: 'Компаниуд',
    rolePermissions: 'Эрхийн тохиргоо',
    modules: 'Модулиуд',
    changePassword: 'Нууц үг солих',
  },
  ja: {
    home: 'ホーム',
    windows: 'ウィンドウ',
    help: 'ヘルプ',
    welcome: 'ようこそ',
    logout: 'ログアウト',
    pinned: 'ピン留め',
    dashboard: 'ダッシュボード',
    forms: 'フォーム',
    reports: 'レポート',
    settings: '設定',
    general: '一般',
    users: 'ユーザー',
    userCompanies: 'ユーザー企業',
    rolePermissions: 'ロール権限',
    modules: 'モジュール',
    changePassword: 'パスワード変更',
  },
  ko: {
    home: '홈',
    windows: '창',
    help: '도움말',
    welcome: '환영합니다',
    logout: '로그아웃',
    pinned: '고정됨',
    dashboard: '대시보드',
    forms: '양식',
    reports: '보고서',
    settings: '설정',
    general: '일반',
    users: '사용자',
    userCompanies: '사용자 회사',
    rolePermissions: '역할 권한',
    modules: '모듈',
    changePassword: '비밀번호 변경',
  },
  zh: {
    home: '首页',
    windows: '窗口',
    help: '帮助',
    welcome: '欢迎',
    logout: '退出',
    pinned: '已固定',
    dashboard: '仪表板',
    forms: '表单',
    reports: '报告',
    settings: '设置',
    general: '常规',
    users: '用户',
    userCompanies: '用户公司',
    rolePermissions: '角色权限',
    modules: '模块',
    changePassword: '更改密码',
  },
  es: {
    home: 'Inicio',
    windows: 'Ventanas',
    help: 'Ayuda',
    welcome: 'Bienvenido',
    logout: 'Cerrar sesión',
    pinned: 'Fijado',
    dashboard: 'Tablero',
    forms: 'Formularios',
    reports: 'Informes',
    settings: 'Configuración',
    general: 'General',
    users: 'Usuarios',
    userCompanies: 'Empresas',
    rolePermissions: 'Permisos de rol',
    modules: 'Módulos',
    changePassword: 'Cambiar contraseña',
  },
  de: {
    home: 'Startseite',
    windows: 'Fenster',
    help: 'Hilfe',
    welcome: 'Willkommen',
    logout: 'Abmelden',
    pinned: 'Angeheftet',
    dashboard: 'Dashboard',
    forms: 'Formulare',
    reports: 'Berichte',
    settings: 'Einstellungen',
    general: 'Allgemein',
    users: 'Benutzer',
    userCompanies: 'Unternehmen',
    rolePermissions: 'Rollenberechtigungen',
    modules: 'Module',
    changePassword: 'Passwort ändern',
  },
  fr: {
    home: 'Accueil',
    windows: 'Fenêtres',
    help: 'Aide',
    welcome: 'Bienvenue',
    logout: 'Déconnexion',
    pinned: 'Épinglé',
    dashboard: 'Tableau de bord',
    forms: 'Formulaires',
    reports: 'Rapports',
    settings: 'Paramètres',
    general: 'Général',
    users: 'Utilisateurs',
    userCompanies: 'Entreprises',
    rolePermissions: 'Autorisations de rôle',
    modules: 'Modules',
    changePassword: 'Changer le mot de passe',
  },
  ru: {
    home: 'Главная',
    windows: 'Окна',
    help: 'Помощь',
    welcome: 'Добро пожаловать',
    logout: 'Выход',
    pinned: 'Закреплено',
    dashboard: 'Панель',
    forms: 'Формы',
    reports: 'Отчеты',
    settings: 'Настройки',
    general: 'Общие',
    users: 'Пользователи',
    userCompanies: 'Компании',
    rolePermissions: 'Права ролей',
    modules: 'Модули',
    changePassword: 'Сменить пароль',
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  useEffect(() => {
    localStorage.setItem('lang', lang);
  }, [lang]);

  const t = useMemo(() => {
    const dict = translations[lang] || translations.en;
    return (key) => dict[key] || translations.en[key] || key;
  }, [lang]);

  const value = useMemo(() => ({ lang, setLang, t }), [lang, t]);

  return <LangContext.Provider value={value}>{children}</LangContext.Provider>;
}

export default LangContext;

