CREATE TABLE IF NOT EXISTS `code_edhorongo_other` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `ehkod` VARCHAR(21),
  `company_id` INT,
  `ehkod_name` VARCHAR(255),
  `ehkod_mu` VARCHAR(21),
  `ehkod_muid` INT,
  `ehkod_price` DECIMAL(18,2),
  `ehkod_size` VARCHAR(21),
  `ehkod_width` VARCHAR(21),
  `ehkod_date` DATE,
  `ehkod_slength` VARCHAR(21),
  `ehkod_swidth` VARCHAR(21),
  `ehkod_spec` VARCHAR(255),
  `ehkod_balance` INT,
  `ehkod_desc` VARCHAR(255),
  `ehkod_room` VARCHAR(21),
  `ehkod_holder` VARCHAR(21),
  `ehkod_tur` VARCHAR(1),
  `ehkod_bairshil` VARCHAR(21),
  `ehkod_negjtalbar` VARCHAR(1),
  `ehkod_zoriulalt` VARCHAR(255),
  `ehkod_type` VARCHAR(1),
  `ehkod_angilal` VARCHAR(1),
  `error_description` VARCHAR(255)
);-- Progress: Group 1 of 1
INSERT INTO `code_edhorongo_other` (`ehkod`, `company_id`, `ehkod_name`, `ehkod_mu`, `ehkod_muid`, `ehkod_price`, `ehkod_size`, `ehkod_width`, `ehkod_date`, `ehkod_slength`, `ehkod_swidth`, `ehkod_spec`, `ehkod_balance`, `ehkod_desc`, `ehkod_room`, `ehkod_holder`, `ehkod_tur`, `ehkod_bairshil`, `ehkod_negjtalbar`, `ehkod_zoriulalt`, `ehkod_type`, `ehkod_angilal`, `category`, `error_description`) VALUES ('0', 2, '0', '0', 0, NULL, '0', '0', NULL, '0', '0', '0', 0, '0', NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, 'duplicate: ehkod, company_id'), ('0', 2, '0', '0', 0, NULL, '0', '0', NULL, '0', '0', '0', 0, '0', NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, 'duplicate: ehkod, company_id'), ('0', 2, '0', '0', 0, NULL, '0', '0', NULL, '0', '0', '0', 0, '0', NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, NULL, 'duplicate: ehkod, company_id') ON DUPLICATE KEY UPDATE `ehkod` = VALUES(`ehkod`), `company_id` = VALUES(`company_id`), `ehkod_name` = VALUES(`ehkod_name`), `ehkod_mu` = VALUES(`ehkod_mu`), `ehkod_muid` = VALUES(`ehkod_muid`), `ehkod_price` = VALUES(`ehkod_price`), `ehkod_size` = VALUES(`ehkod_size`), `ehkod_width` = VALUES(`ehkod_width`), `ehkod_date` = VALUES(`ehkod_date`), `ehkod_slength` = VALUES(`ehkod_slength`), `ehkod_swidth` = VALUES(`ehkod_swidth`), `ehkod_spec` = VALUES(`ehkod_spec`), `ehkod_balance` = VALUES(`ehkod_balance`), `ehkod_desc` = VALUES(`ehkod_desc`), `ehkod_room` = VALUES(`ehkod_room`), `ehkod_holder` = VALUES(`ehkod_holder`), `ehkod_tur` = VALUES(`ehkod_tur`), `ehkod_bairshil` = VALUES(`ehkod_bairshil`), `ehkod_negjtalbar` = VALUES(`ehkod_negjtalbar`), `ehkod_zoriulalt` = VALUES(`ehkod_zoriulalt`), `ehkod_type` = VALUES(`ehkod_type`), `ehkod_angilal` = VALUES(`ehkod_angilal`), `category` = VALUES(`category`), `error_description` = VALUES(`error_description`);

CREATE TABLE IF NOT EXISTS `code_edhorongo` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `ehkod` VARCHAR(21) NOT NULL,
  `company_id` INT NOT NULL,
  `ehkod_name` VARCHAR(255),
  `ehkod_mu` VARCHAR(21),
  `ehkod_muid` INT,
  `ehkod_price` DECIMAL(18,2),
  `ehkod_size` VARCHAR(21),
  `ehkod_width` VARCHAR(21),
  `ehkod_date` DATE,
  `ehkod_slength` VARCHAR(21),
  `ehkod_swidth` VARCHAR(21),
  `ehkod_spec` VARCHAR(255),
  `ehkod_balance` INT,
  `ehkod_desc` VARCHAR(255),
  `ehkod_room` VARCHAR(21),
  `ehkod_holder` VARCHAR(21),
  `ehkod_tur` VARCHAR(1),
  `ehkod_bairshil` VARCHAR(21),
  `ehkod_negjtalbar` VARCHAR(1),
  `ehkod_zoriulalt` VARCHAR(255),
  `ehkod_type` VARCHAR(1),
  `ehkod_angilal` VARCHAR(1),
  UNIQUE KEY uniq_ehkod_company_id (`ehkod`, `company_id`)
) AUTO_INCREMENT=1;