START TRANSACTION;

CREATE TABLE IF NOT EXISTS plan_header (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  plan_no VARCHAR(50) NOT NULL,
  plan_type_code VARCHAR(50) NOT NULL,
  plan_category_code VARCHAR(50) NULL,
  parent_plan_id BIGINT NULL,
  source_transaction_table VARCHAR(100) NULL,
  source_transaction_id BIGINT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT NULL,
  strategic_level ENUM('strategic','program','operational','task','investigation','budget') NOT NULL,
  status_code VARCHAR(50) NOT NULL,
  priority_code VARCHAR(50) NULL,
  risk_level_code VARCHAR(50) NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  target_date DATE NULL,
  owner_empid VARCHAR(20) NULL,
  initiator_empid VARCHAR(20) NULL,
  approved_by_empid VARCHAR(20) NULL,
  approved_at DATETIME NULL,
  closed_by_empid VARCHAR(20) NULL,
  closed_at DATETIME NULL,
  currency_code VARCHAR(10) NULL,
  version_no INT NOT NULL DEFAULT 1,
  is_template TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_plan_header_plan_no (plan_no),
  KEY idx_plan_header_company_type (company_id, plan_type_code),
  KEY idx_plan_header_company_status (company_id, status_code),
  KEY idx_plan_header_company_owner (company_id, owner_empid),
  KEY idx_plan_header_company_level (company_id, strategic_level),
  KEY idx_plan_header_company_dates (company_id, start_date, end_date),
  KEY idx_plan_header_source_txn (source_transaction_table, source_transaction_id),
  CONSTRAINT fk_plan_header_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_plan_header_parent_plan FOREIGN KEY (parent_plan_id) REFERENCES plan_header(id)
);

CREATE TABLE IF NOT EXISTS plan_line (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  plan_id BIGINT NOT NULL,
  line_no INT NOT NULL,
  line_type_code VARCHAR(50) NOT NULL,
  parent_line_id BIGINT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT NULL,
  target_value DECIMAL(18,4) NULL,
  actual_value DECIMAL(18,4) NULL,
  unit_code VARCHAR(50) NULL,
  weight_pct DECIMAL(8,4) NULL,
  status_code VARCHAR(50) NOT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  owner_empid VARCHAR(20) NULL,
  completion_pct DECIMAL(8,4) NULL,
  notes TEXT NULL,
  created_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_plan_line_company_plan (company_id, plan_id),
  KEY idx_plan_line_company_status (company_id, status_code),
  KEY idx_plan_line_company_owner (company_id, owner_empid),
  KEY idx_plan_line_company_type (company_id, line_type_code),
  CONSTRAINT fk_plan_line_plan FOREIGN KEY (plan_id) REFERENCES plan_header(id),
  CONSTRAINT fk_plan_line_parent_line FOREIGN KEY (parent_line_id) REFERENCES plan_line(id)
);

CREATE TABLE IF NOT EXISTS plan_assignment (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  plan_id BIGINT NOT NULL,
  plan_line_id BIGINT NULL,
  assignment_type ENUM('owner','executor','reviewer','approver','observer','auditor') NOT NULL,
  empid VARCHAR(20) NULL,
  department_id INT NULL,
  position_id INT NULL,
  workplace_id INT NULL,
  assigned_from DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  assigned_to DATETIME NULL,
  status_code VARCHAR(50) NOT NULL,
  notes TEXT NULL,
  created_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_plan_assignment_company_plan (company_id, plan_id),
  KEY idx_plan_assignment_company_empid (company_id, empid),
  KEY idx_plan_assignment_company_department (company_id, department_id),
  KEY idx_plan_assignment_company_workplace (company_id, workplace_id),
  KEY idx_plan_assignment_company_type_status (company_id, assignment_type, status_code),
  CONSTRAINT fk_plan_assignment_plan FOREIGN KEY (plan_id) REFERENCES plan_header(id),
  CONSTRAINT fk_plan_assignment_line FOREIGN KEY (plan_line_id) REFERENCES plan_line(id)
);

CREATE TABLE IF NOT EXISTS plan_resource_allocation (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  plan_id BIGINT NOT NULL,
  plan_line_id BIGINT NULL,
  resource_type ENUM('material','inventory','employee','position','equipment','vehicle','service','cash','budget','other') NOT NULL,
  resource_table VARCHAR(100) NULL,
  resource_record_id BIGINT NULL,
  resource_code VARCHAR(100) NULL,
  quantity_planned DECIMAL(18,4) NULL,
  quantity_allocated DECIMAL(18,4) NULL,
  quantity_used DECIMAL(18,4) NULL,
  unit_code VARCHAR(50) NULL,
  amount_planned DECIMAL(18,2) NULL,
  amount_allocated DECIMAL(18,2) NULL,
  amount_used DECIMAL(18,2) NULL,
  currency_code VARCHAR(10) NULL,
  allocation_status_code VARCHAR(50) NOT NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  notes TEXT NULL,
  created_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_plan_resource_company_plan (company_id, plan_id),
  KEY idx_plan_resource_company_type (company_id, resource_type),
  KEY idx_plan_resource_record (resource_table, resource_record_id),
  KEY idx_plan_resource_company_status (company_id, allocation_status_code),
  CONSTRAINT fk_plan_resource_plan FOREIGN KEY (plan_id) REFERENCES plan_header(id),
  CONSTRAINT fk_plan_resource_line FOREIGN KEY (plan_line_id) REFERENCES plan_line(id)
);

CREATE TABLE IF NOT EXISTS plan_completion (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  plan_id BIGINT NOT NULL,
  plan_line_id BIGINT NULL,
  completion_type_code VARCHAR(50) NOT NULL,
  completion_date DATETIME NOT NULL,
  completion_pct DECIMAL(8,4) NULL,
  result_text TEXT NULL,
  evidence_table VARCHAR(100) NULL,
  evidence_record_id BIGINT NULL,
  verified_by_empid VARCHAR(20) NULL,
  verified_at DATETIME NULL,
  created_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_plan_completion_company_plan (company_id, plan_id),
  KEY idx_plan_completion_company_date (company_id, completion_date),
  KEY idx_plan_completion_company_type (company_id, completion_type_code),
  KEY idx_plan_completion_evidence (evidence_table, evidence_record_id),
  CONSTRAINT fk_plan_completion_plan FOREIGN KEY (plan_id) REFERENCES plan_header(id),
  CONSTRAINT fk_plan_completion_line FOREIGN KEY (plan_line_id) REFERENCES plan_line(id)
);

CREATE TABLE IF NOT EXISTS budget_header (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  budget_no VARCHAR(50) NOT NULL,
  budget_name VARCHAR(255) NOT NULL,
  budget_type_code VARCHAR(50) NOT NULL,
  budget_scope_code VARCHAR(50) NOT NULL,
  fiscal_year INT NOT NULL,
  period_type_code VARCHAR(50) NOT NULL,
  scenario_code VARCHAR(50) NOT NULL,
  version_no INT NOT NULL DEFAULT 1,
  status_code VARCHAR(50) NOT NULL,
  base_budget_id BIGINT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  currency_code VARCHAR(10) NOT NULL,
  owner_empid VARCHAR(20) NULL,
  approved_by_empid VARCHAR(20) NULL,
  approved_at DATETIME NULL,
  locked_at DATETIME NULL,
  notes TEXT NULL,
  created_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_budget_header_budget_no (budget_no),
  KEY idx_budget_header_company_year (company_id, fiscal_year),
  KEY idx_budget_header_company_status (company_id, status_code),
  KEY idx_budget_header_company_scenario (company_id, scenario_code),
  KEY idx_budget_header_company_type (company_id, budget_type_code),
  CONSTRAINT fk_budget_header_base_budget FOREIGN KEY (base_budget_id) REFERENCES budget_header(id)
);

CREATE TABLE IF NOT EXISTS budget_line (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  budget_id BIGINT NOT NULL,
  line_no INT NOT NULL,
  account_code VARCHAR(50) NULL,
  dr_cr_flag CHAR(1) NULL,
  dimension_set_id BIGINT NULL,
  period_key VARCHAR(20) NOT NULL,
  branch_id INT NULL,
  department_id INT NULL,
  workplace_id INT NULL,
  project_id BIGINT NULL,
  plan_id BIGINT NULL,
  resource_type VARCHAR(50) NULL,
  resource_code VARCHAR(100) NULL,
  amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  quantity DECIMAL(18,4) NULL,
  unit_code VARCHAR(50) NULL,
  notes TEXT NULL,
  created_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_budget_line_company_budget (company_id, budget_id),
  KEY idx_budget_line_company_account_period (company_id, account_code, period_key),
  KEY idx_budget_line_company_org_period (company_id, branch_id, department_id, period_key),
  KEY idx_budget_line_company_project_period (company_id, project_id, period_key),
  KEY idx_budget_line_company_plan (company_id, plan_id),
  CONSTRAINT fk_budget_line_budget FOREIGN KEY (budget_id) REFERENCES budget_header(id),
  CONSTRAINT fk_budget_line_plan FOREIGN KEY (plan_id) REFERENCES plan_header(id)
);

CREATE TABLE IF NOT EXISTS budget_consumption (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  budget_id BIGINT NOT NULL,
  budget_line_id BIGINT NULL,
  source_table VARCHAR(100) NOT NULL,
  source_record_id BIGINT NOT NULL,
  journal_id BIGINT NULL,
  period_key VARCHAR(20) NOT NULL,
  amount_consumed DECIMAL(18,2) NOT NULL DEFAULT 0,
  quantity_consumed DECIMAL(18,4) NULL,
  consumed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_budget_consumption_company_budget (company_id, budget_id),
  KEY idx_budget_consumption_company_line (company_id, budget_line_id),
  KEY idx_budget_consumption_source (source_table, source_record_id),
  KEY idx_budget_consumption_company_period (company_id, period_key),
  CONSTRAINT fk_budget_consumption_budget FOREIGN KEY (budget_id) REFERENCES budget_header(id),
  CONSTRAINT fk_budget_consumption_line FOREIGN KEY (budget_line_id) REFERENCES budget_line(id)
);

CREATE TABLE IF NOT EXISTS business_rule_header (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  rule_code VARCHAR(100) NOT NULL,
  rule_name VARCHAR(255) NOT NULL,
  rule_group_code VARCHAR(50) NOT NULL,
  rule_domain ENUM('financial','planning','budgeting','inventory','notification','dashboard','ai','approval','security','generic') NOT NULL,
  trigger_event ENUM('insert','update','delete','status_change','approval','period_close','manual','scheduled') NOT NULL,
  source_table VARCHAR(100) NULL,
  source_transaction_type VARCHAR(50) NULL,
  target_action_code VARCHAR(50) NOT NULL,
  priority_no INT NOT NULL DEFAULT 100,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  stop_on_match TINYINT(1) NOT NULL DEFAULT 0,
  effective_from DATETIME NULL,
  effective_to DATETIME NULL,
  notes TEXT NULL,
  created_by VARCHAR(50) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(50) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  UNIQUE KEY uq_business_rule_header_rule_code (rule_code),
  KEY idx_business_rule_header_domain_active (company_id, rule_domain, is_active),
  KEY idx_business_rule_header_event_active (company_id, trigger_event, is_active),
  KEY idx_business_rule_header_source_type (company_id, source_table, source_transaction_type),
  KEY idx_business_rule_header_priority (company_id, priority_no)
);

CREATE TABLE IF NOT EXISTS business_rule_condition (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  rule_id BIGINT NOT NULL,
  group_no INT NOT NULL DEFAULT 1,
  seq_no INT NOT NULL DEFAULT 1,
  left_source_type ENUM('field','constant','sql','dimension','session','function') NOT NULL,
  left_table_name VARCHAR(100) NULL,
  left_field_name VARCHAR(100) NULL,
  operator_code VARCHAR(50) NOT NULL,
  right_source_type ENUM('field','constant','sql','dimension','session','function') NOT NULL,
  right_table_name VARCHAR(100) NULL,
  right_field_name VARCHAR(100) NULL,
  constant_value TEXT NULL,
  logic_join_code ENUM('AND','OR') NOT NULL DEFAULT 'AND',
  open_bracket_count INT NOT NULL DEFAULT 0,
  close_bracket_count INT NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  KEY idx_business_rule_condition_rule_seq (company_id, rule_id, group_no, seq_no),
  CONSTRAINT fk_business_rule_condition_rule FOREIGN KEY (rule_id) REFERENCES business_rule_header(id)
);

CREATE TABLE IF NOT EXISTS business_rule_action (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  rule_id BIGINT NOT NULL,
  seq_no INT NOT NULL DEFAULT 1,
  action_type ENUM('create_transaction','create_plan','create_budget_line','create_notification','write_journal','call_procedure','update_field','block_transaction','request_approval','ai_analyze','ai_notify') NOT NULL,
  target_table VARCHAR(100) NULL,
  target_transaction_type VARCHAR(50) NULL,
  procedure_name VARCHAR(150) NULL,
  config_json JSON NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  KEY idx_business_rule_action_rule_seq (company_id, rule_id, seq_no),
  KEY idx_business_rule_action_type (company_id, action_type),
  CONSTRAINT fk_business_rule_action_rule FOREIGN KEY (rule_id) REFERENCES business_rule_header(id)
);

CREATE TABLE IF NOT EXISTS business_dimension_map (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  dimension_code VARCHAR(100) NOT NULL,
  dimension_name VARCHAR(255) NOT NULL,
  source_table VARCHAR(100) NOT NULL,
  source_field VARCHAR(100) NOT NULL,
  source_value_field VARCHAR(100) NULL,
  source_label_field VARCHAR(100) NULL,
  data_type_code VARCHAR(50) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  notes TEXT NULL,
  UNIQUE KEY uq_business_dimension_map_company_code (company_id, dimension_code),
  KEY idx_business_dimension_map_source (company_id, source_table, source_field)
);

CREATE TABLE IF NOT EXISTS rule_execution_log (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  company_id INT NOT NULL,
  rule_id BIGINT NOT NULL,
  source_table VARCHAR(100) NOT NULL,
  source_record_id BIGINT NOT NULL,
  trigger_event VARCHAR(50) NOT NULL,
  matched_flag TINYINT(1) NOT NULL DEFAULT 0,
  execution_status VARCHAR(50) NOT NULL,
  message TEXT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME NULL,
  created_by VARCHAR(50) NULL,
  KEY idx_rule_execution_log_rule_started (company_id, rule_id, started_at),
  KEY idx_rule_execution_log_source (source_table, source_record_id),
  KEY idx_rule_execution_log_status (company_id, execution_status),
  CONSTRAINT fk_rule_execution_log_rule FOREIGN KEY (rule_id) REFERENCES business_rule_header(id)
);

COMMIT;
