version: 1

deployment:
  tasks:
    # 1) production package install
    - /usr/bin/npm install --omit=dev

    # 2) Passenger (Application Manager) хэрэглэж буй тул
    #    restart-хийн тулд tmp/restart.txt дээр touch хийдэг
    - /usr/bin/touch tmp/restart.txt
