---
deployment:
  tasks:
    - mkdir -p ~/public_html ~/public_html/erp
    - rm -rf node_modules
    - npm install --no-progress
    - npm run build:homepage
    - npm run build:erp
    - cp src/erp.mgt.mn/.htaccess ~/public_html/erp/.htaccess
    - npm prune --omit=dev
