---
deployment:
  tasks:
    - /bin/bash -lc 'set -euo pipefail'

    # Deploy homepage
    - /bin/bash -lc 'rsync -a --delete ./build_home/ "$HOME/public_html/"'

    # Deploy ERP
    - /bin/bash -lc 'rsync -a --delete ./build_erp/ "$HOME/erp.mgt.mn/"'

    # Restart backend app
    - /bin/bash -lc 'pm2 restart erp-app --update-env || true'

    - /bin/echo "[cpanel] Deploy finished: $(date -Is)"
