name: CI/CD Pipeline
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --no-progress
      - name: Build
        run: npm run build -- --base=/erp/
      - name: Deploy to cPanel
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_KEY }}
          source: "dist/*"
          target: "~/apps/erp-web-next/dist"