openapi: 3.1.0
x-stoplight:
  id: lq7opcr2vsf10
info:
  title: Зөвшөөрлийн цахим систем
  version: '1.0'
  contact:
    name: ЗЦС
    email: enkhzaya@itc.gov.mn
  summary: Зөвшөөрлийн цахим систем
  termsOfService: ''
  description: Хуулийн этгээдийн зөвшөөрлийн мэдээлэл лавлах
servers:
  - url: st-license.mof.gov.mn
    description: Туршилтын орчин
  - url: license.mn
    description: Бодит орчин
paths:
  'https://license.mn/license-report-service/xyp/getUserOrganizationLicenses':
    parameters: []
    get:
      summary: Хуулийн этгээдийн зөвшөөрлийн мэдээлэл шалгах
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    x-stoplight:
                      id: 6ddb7ywxrahdx
                    description: Байгууллагын нэр
                  regno:
                    type: string
                    x-stoplight:
                      id: ymazl7g3bekoa
                    description: Байгууллагын регистр
                  licenseName:
                    type: string
                    x-stoplight:
                      id: lmmbtnkx1s7sk
                    description: Зөвшөөрлийн нэр
                  licenseType:
                    type: string
                    x-stoplight:
                      id: 0xe1ytngig65q
                    description: Зөвшөөрлийн төрөл
                  orgName:
                    type: string
                    x-stoplight:
                      id: lwd0gybh5t131
                    description: Зөвшөөрөл олгосон эрх бүхий байгууллага
                  orgRegno:
                    type: string
                    x-stoplight:
                      id: j248o7wwlb3wj
                    description: Зөвшөөрөл олгосон эрх бүхий байгууллагын регистр
                  startDate:
                    type: string
                    x-stoplight:
                      id: b70met7r1ha6i
                    description: Олгосон огноо
                  endDate:
                    type: string
                    x-stoplight:
                      id: etppo20rug4su
                    description: Дуусах огноо
                  status:
                    type: string
                    x-stoplight:
                      id: 357foyodo0gm5
                    description: Зөвшөөрлийн төлөв
        '404':
          description: Not_Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: rest/license-report-service/xyp/getUserOrganizationLicenses
      description: "> ### Хуулийн этгээдэд олгосон зөвшөөрлийн мэдээлэл шалгах\r\n### Гаралтыг утгын тайлбар:\r\n | Утга  | Тайлбар  | \r\n---------|----------|\r\n | OK | Амжилттай | \r\n NOT_FOUND | Зөвшөөрлийн мэдээлэл олдсонгүй\r\n\r\n \r\n ### Ваучерын төрлийн тайлбар:\r\n | Утга  | Тайлбар  | \r\n---------|----------|\r\n 1 | Байгууллагын нэр| \r\n 2 | Регистрийн дугаар | \r\n 3 | Зөвшөөрлийн нэр | \r\n 4 | Зөвшөөрлийн төрөл\r\n 5 | Зөвшөөрөл олгосон эрх бүхий байгууллага\r\n 6 | Зөвшөөрөл олгосон эрх бүхий байгууллагын регистр\r\n 7 | Олгосон огноо\r\n 8 | Дууссан огноо \r\n 9 | Төлөв\r\n"
      x-stoplight:
        id: ewy1w2bkjyta2
      requestBody:
        content: {}
      parameters:
        - schema:
            type: string
          in: query
          name: regno
          description: Байгууллагын регистр
      x-internal: false
    servers:
      - url: 'https://st-license.mof.gov.mn'
        description: Туршилтын орчин
      - url: 'https://license.mn'
        description: Бодит орчин
  rest/license-report-service/xyp/getUserLicenses:
    parameters: []
    get:
      summary: Иргэнд олгосон зөвшөөрлийн мэдээлэл шалгах
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Хэрэглэгчийн овог нэр
                  regno:
                    type: string
                    description: Иргэний регистр
                  licenseName:
                    type: string
                    description: Зөвшөөрлийн нэр
                  licenseType:
                    type: string
                    description: Зөвшөөрлийн төрөл
                  orgName:
                    type: string
                    description: Зөвшөөрөл олгосон эрх бүхий байгууллага
                  orgRegno:
                    type: string
                    description: Зөвшөөрөл олгосон эрх бүхий байгууллагын регистр
                  startDate:
                    type: string
                    description: Олгосон огноо
                  endDate:
                    type: string
                    description: Дуусах огноо
                  status:
                    type: string
                    description: Зөвшөөрлийн төлөв
        '404':
          description: Not_Found
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: rest/license-report-service/xyp/getUserOrganizationLicenses
      description: "> ### Иргэнд олгосон зөвшөөрлийн мэдээлэл шалгах\r\n### Гаралтыг утгын тайлбар:\r\n | Утга  | Тайлбар  | \r\n---------|----------|\r\n | OK | Амжилттай | \r\n NOT_FOUND | Зөвшөөрлийн мэдээлэл олдсонгүй\r\n\r\n \r\n ### Ваучерын төрлийн тайлбар:\r\n | Утга  | Тайлбар  | \r\n---------|----------|\r\n 1 |Хэрэглэгчийн овог, нэр| \r\n 2 | Регистрийн дугаар | \r\n 3 | Зөвшөөрлийн нэр | \r\n 4 | Зөвшөөрлийн төрөл\r\n 5 | Зөвшөөрөл олгосон эрх бүхий байгууллага\r\n 6 | Зөвшөөрөл олгосон эрх бүхий байгууллагын регистр\r\n 7 | Олгосон огноо\r\n 8 | Дууссан огноо \r\n 9 | Төлөв\r\n"
      requestBody:
        content: {}
      parameters:
        - schema:
            type: string
          in: query
          name: regno
          description: Иргэний регистрийн дугаар
      x-stoplight:
        id: r9oand11youf9
      x-internal: false
    servers:
      - url: 'https://st-license.mof.gov.mn'
        description: Туршилтын орчин
      - url: 'https://license.mn'
        description: Бодит орчин
components:
  schemas: {}
x-internal: false
