openapi: 3.1.0
info:
  version: '1.0'
  title: Зөвшөөрлийн цахим систем
  summary: Зөвшөөрлийн цахим систем
  description: Хуулийн этгээдийн зөвшөөрлийн мэдээлэл лавлах
  termsOfService: ''
  contact:
    name: ЗЦС
    email: enkhzaya@itc.gov.mn
servers:
  - url: st-license.mof.gov.mn
    description: Туршилтын орчин
  - url: license.mn
    description: Бодит орчин
paths:
  'https://license.mn/license-report-service/xyp/getUserOrganizationLicenses':
    get:
      summary: Хуулийн этгээдийн зөвшөөрлийн мэдээлэл шалгах
      description: "> ### Хуулийн этгээдэд олгосон зөвшөөрлийн мэдээлэл шалгах\r\n### Гаралтыг утгын тайлбар:\r\n | Утга  | Тайлбар  | \r\n---------|----------|\r\n | OK | Амжилттай | \r\n NOT_FOUND | Зөвшөөрлийн мэдээлэл олдсонгүй\r\n\r\n \r\n ### Ваучерын төрлийн тайлбар:\r\n | Утга  | Тайлбар  | \r\n---------|----------|\r\n 1 | Байгууллагын нэр| \r\n 2 | Регистрийн дугаар | \r\n 3 | Зөвшөөрлийн нэр | \r\n 4 | Зөвшөөрлийн төрөл\r\n 5 | Зөвшөөрөл олгосон эрх бүхий байгууллага\r\n 6 | Зөвшөөрөл олгосон эрх бүхий байгууллагын регистр\r\n 7 | Олгосон огноо\r\n 8 | Дууссан огноо \r\n 9 | Төлөв\r\n"
      operationId: rest/license-report-service/xyp/getUserOrganizationLicenses
      parameters:
        - name: regno
          in: query
          description: Байгууллагын регистр
          schema:
            type: string
      requestBody:
        content: {}
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Байгууллагын нэр
                  regno:
                    type: string
                    description: Байгууллагын регистр
                  licenseName:
                    type: string
                    description: Зөвшөөрлийн нэр
                  licenseType:
                    type: string
                    description: Зөвшөөрлийн төрөл
                  orgName:
                    type: string
                    description: Зөвшөөрөл олгосон эрх бүхий байгууллага
                  orgRegno:
                    type: string
                    description: Зөвшөөрөл олгосон эрх бүхий байгууллагын регистр
                  startDate:
                    type: string
                    description: Олгосон огноо
                  endDate:
                    type: string
                    description: Дуусах огноо
                  status:
                    type: string
                    description: Зөвшөөрлийн төлөв
        '404':
          description: Not_Found
          content:
            application/json:
              schema:
                type: object
      servers:
        - url: 'https://st-license.mof.gov.mn'
          description: Туршилтын орчин
        - url: 'https://license.mn'
          description: Бодит орчин
      x-internal: false
  rest/license-report-service/xyp/getUserLicenses:
    get:
      summary: Иргэнд олгосон зөвшөөрлийн мэдээлэл шалгах
      description: "> ### Иргэнд олгосон зөвшөөрлийн мэдээлэл шалгах\r\n### Гаралтыг утгын тайлбар:\r\n | Утга  | Тайлбар  | \r\n---------|----------|\r\n | OK | Амжилттай | \r\n NOT_FOUND | Зөвшөөрлийн мэдээлэл олдсонгүй\r\n\r\n \r\n ### Ваучерын төрлийн тайлбар:\r\n | Утга  | Тайлбар  | \r\n---------|----------|\r\n 1 |Хэрэглэгчийн овог, нэр| \r\n 2 | Регистрийн дугаар | \r\n 3 | Зөвшөөрлийн нэр | \r\n 4 | Зөвшөөрлийн төрөл\r\n 5 | Зөвшөөрөл олгосон эрх бүхий байгууллага\r\n 6 | Зөвшөөрөл олгосон эрх бүхий байгууллагын регистр\r\n 7 | Олгосон огноо\r\n 8 | Дууссан огноо \r\n 9 | Төлөв\r\n"
      operationId: rest/license-report-service/xyp/getUserOrganizationLicenses
      parameters:
        - name: regno
          in: query
          description: Иргэний регистрийн дугаар
          schema:
            type: string
      requestBody:
        content: {}
      responses:
        '200':
          description: OK
          content:
            application/xml:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Хэрэглэгчийн овог нэр
                  regno:
                    type: string
                    description: Иргэний регистр
                  licenseName:
                    type: string
                    description: Зөвшөөрлийн нэр
                  licenseType:
                    type: string
                    description: Зөвшөөрлийн төрөл
                  orgName:
                    type: string
                    description: Зөвшөөрөл олгосон эрх бүхий байгууллага
                  orgRegno:
                    type: string
                    description: Зөвшөөрөл олгосон эрх бүхий байгууллагын регистр
                  startDate:
                    type: string
                    description: Олгосон огноо
                  endDate:
                    type: string
                    description: Дуусах огноо
                  status:
                    type: string
                    description: Зөвшөөрлийн төлөв
        '404':
          description: Not_Found
          content:
            application/json:
              schema:
                type: object
      servers:
        - url: 'https://st-license.mof.gov.mn'
          description: Туршилтын орчин
        - url: 'https://license.mn'
          description: Бодит орчин
      x-internal: false
x-internal: false
