export default [
  { moduleKey: 'action_permissions', label: 'Action Permissions', parentKey: 'developer', showInSidebar: true, showInHeader: false },
  { moduleKey: 'ai_inventory', label: 'AI Inventory Review', parentKey: null, showInSidebar: true, showInHeader: false },
  { moduleKey: 'ai-inventory', label: 'ai-inventory', parentKey: null, showInSidebar: true, showInHeader: false },
  { moduleKey: 'change_password', label: 'Нууц үг солих', parentKey: 'settings', showInSidebar: true, showInHeader: false },
  { moduleKey: 'coding_tables', label: 'Кодын хүснэгтүүд', parentKey: 'developer', showInSidebar: true, showInHeader: false },
  { moduleKey: 'company_licenses', label: 'Лиценз', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'dashboard', label: 'Самбар', parentKey: null, showInSidebar: true, showInHeader: false },
  { moduleKey: 'developer', label: 'Хөгжүүлэгч', parentKey: null, showInSidebar: true, showInHeader: false },
  { moduleKey: 'error_log', label: 'Алдааны түүх', parentKey: 'developer', showInSidebar: true, showInHeader: false },
  { moduleKey: 'finance_transactions', label: 'САНХҮҮ БҮРТГЭЛ', parentKey: 'forms', showInSidebar: true, showInHeader: false },
  { moduleKey: 'forms', label: 'Маягтууд', parentKey: null, showInSidebar: true, showInHeader: false },
  { moduleKey: 'forms_management', label: 'Маягтын удирдлага', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'general_configuration', label: 'Ерөнхий тохиргоо', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'gl', label: 'Ерөнхий журнал', parentKey: null, showInSidebar: false, showInHeader: true },
  { moduleKey: 'image_management', label: 'Image Management', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'inventory_transaction', label: 'БАРАА МАТЕРИАЛ', parentKey: 'forms', showInSidebar: true, showInHeader: false },
  { moduleKey: 'manuals', label: 'Гарын авлага', parentKey: null, showInSidebar: false, showInHeader: true },
  { moduleKey: 'modules', label: 'Модуль', parentKey: 'developer', showInSidebar: true, showInHeader: false },
  { moduleKey: 'planning_transactions', label: 'АЖЛЫН ТӨЛӨВЛӨЛӨЛТ', parentKey: 'forms', showInSidebar: true, showInHeader: false },
  { moduleKey: 'po', label: 'Худалдан авалтын захиалга', parentKey: null, showInSidebar: false, showInHeader: true },
  { moduleKey: 'pos_transaction_management', label: 'POS Transactions', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'pos_transactions', label: 'POS POS', parentKey: 'forms', showInSidebar: true, showInHeader: false },
  { moduleKey: 'relations_config', label: 'Хүснэгтийн холболт', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'report_builder', label: 'Тайлангийн бүтээгч', parentKey: 'report_management', showInSidebar: true, showInHeader: false },
  { moduleKey: 'report_management', label: 'Тайлангийн удирдлага', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'reports', label: 'Тайлан', parentKey: null, showInSidebar: true, showInHeader: false },
  { moduleKey: 'requests', label: 'Хүсэлтүүд', parentKey: null, showInSidebar: true, showInHeader: null },
  { moduleKey: 'role_permissions', label: 'Эрхийн тохиргоо', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'sales', label: 'Борлуулалтын самбар', parentKey: null, showInSidebar: false, showInHeader: true },
  { moduleKey: 'settings', label: 'Тохиргоо', parentKey: null, showInSidebar: true, showInHeader: false },
  { moduleKey: 'system_configurations', label: 'Системийн тохиргоо', parentKey: null, showInSidebar: true, showInHeader: false },
  { moduleKey: 'tables_management', label: 'Хүснэгтийн удирдлага', parentKey: 'developer', showInSidebar: true, showInHeader: false },
  { moduleKey: 'tenant_tables', label: 'Tenant tables', parentKey: null, showInSidebar: true, showInHeader: false },
  { moduleKey: 'transactions_contract', label: 'Гэрээ', parentKey: 'forms', showInSidebar: true, showInHeader: false },
  { moduleKey: 'user_companies', label: 'Хэрэглэгчийн компаниуд', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'user_level_actions', label: 'User Level Actions', parentKey: 'developer', showInSidebar: true, showInHeader: false },
  { moduleKey: 'user_settings', label: 'Хэрэглэгчийн удирдлага', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
  { moduleKey: 'users', label: 'Хэрэглэгчид', parentKey: 'system_configurations', showInSidebar: true, showInHeader: false },
];
